apiVersion: v1
kind: Service
metadata:
  name: indiaservice
spec:
  selector:
    app: indiaservice  # This matches the app label in the Deployment
  ports:
    - protocol: TCP
      port: 8050            # Expose port 80 externally in the cluster
      targetPort: 8050 
      # nodePort: 30050    # The port your Flask app is running on inside the container
  type: LoadBalancer       # Can be NodePort or LoadBalancer if you need external access
